### ISSUE TITLE
Pollyfill problem after updating to angular 12

### ISSUE THREAD

**Issue by Bidou44** [NativeScript/angular#7] opened 2021-06-16 14:46 UTC
**Environment**
✔ Getting NativeScript components versions information...
✔ Component nativescript has 8.0.2 version and is up to date.
✔ Component @nativescript/core has 8.0.8 version and is up to date.
✔ Component @nativescript/ios has 8.0.0 version and is up to date.
✔ Component @nativescript/android has 8.0.0 version and is up to date.
 
**Describe the bug**
After updating our application to angular 12 by following the blog post under https://blog.nativescript.org/nativescript-angular-12/index.html, I have the following issues

WARNING in ./node_modules/inherits/inherits.js 2:13-28
Module not found: Error: Can't resolve 'util' in '/Users/xxx/node_modules/inherits'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "util": require.resolve("util/") }'
	- install 'util'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "util": false }
 @ ./node_modules/css/lib/stringify/compress.js 7:15-34
 @ ./node_modules/css/lib/stringify/index.js 6:17-38
 @ ./node_modules/css/index.js 2:0-46
 @ ./node_modules/@nativescript/core/ui/styling/style-scope.js 2:0-46 201:32-40
 @ ./node_modules/@nativescript/core/ui/core/view/view-common.js 12:0-55 77:24-34
 @ ./node_modules/@nativescript/core/ui/frame/frame-common.js 8:0-68 521:32-56 600:4-11
 @ ./node_modules/@nativescript/core/ui/frame/index.android.js 3:0-67 13:0-31 13:0-31 59:27-36 89:15-50 92:8-43 95:15-42 98:8-35 278:31-53 327:94-116 578:23-29 1062:49-65

1 warning has detailed information that is not shown.
Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.

ERROR in ./node_modules/css/lib/stringify/source-map-support.js 9:9-22
Module not found: Error: Can't resolve 'fs' in '/Users/xxx/node_modules/css/lib/stringify'
 @ ./node_modules/css/lib/stringify/index.js 32:21-52
 @ ./node_modules/css/index.js 2:0-46
 @ ./node_modules/@nativescript/core/ui/styling/style-scope.js 2:0-46 201:32-40
 @ ./node_modules/@nativescript/core/ui/core/view/view-common.js 12:0-55 77:24-34
 @ ./node_modules/@nativescript/core/ui/frame/frame-common.js 8:0-68 521:32-56 600:4-11
 @ ./node_modules/@nativescript/core/ui/frame/index.android.js 3:0-67 13:0-31 13:0-31 59:27-36 89:15-50 92:8-43 95:15-42 98:8-35 278:31-53 327:94-116 578:23-29 1062:49-65

ERROR in ./node_modules/css/lib/stringify/source-map-support.js 10:11-26
Module not found: Error: Can't resolve 'path' in '/Users/xxx/node_modules/css/lib/stringify'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "path": require.resolve("path-browserify") }'
	- install 'path-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "path": false }
 @ ./node_modules/css/lib/stringify/index.js 32:21-52
 @ ./node_modules/css/index.js 2:0-46
 @ ./node_modules/@nativescript/core/ui/styling/style-scope.js 2:0-46 201:32-40
 @ ./node_modules/@nativescript/core/ui/core/view/view-common.js 12:0-55 77:24-34
 @ ./node_modules/@nativescript/core/ui/frame/frame-common.js 8:0-68 521:32-56 600:4-11
 @ ./node_modules/@nativescript/core/ui/frame/index.android.js 3:0-67 13:0-31 13:0-31 59:27-36 89:15-50 92:8-43 95:15-42 98:8-35 278:31-53 327:94-116 578:23-29 1062:49-65

ERROR in ./node_modules/source-map-resolve/index.js 3:14-29
Module not found: Error: Can't resolve 'path' in '/Users/xxx/node_modules/source-map-resolve'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "path": require.resolve("path-browserify") }'
	- install 'path-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "path": false }

**To Reproduce**
I just followed the blog post under https://blog.nativescript.org/nativescript-angular-12/index.html

**Expected behavior**

**Sample project**

**Additional context**
Angular 12.0.4

**Comment by edusperoni** [comment] 2021-06-16 15:23
Hey @Bidou44!

Can you share your `@nativescript/webpack` version and your `webpack.config.js`?

**Comment by Bidou44** [comment] 2021-06-16 15:36
Hi @edusperoni 

"@nativescript/webpack": "~5.0.0-beta.14"

webpack.config.js
```
const webpack = require("@nativescript/webpack");

module.exports = (env) => {
	webpack.init(env);
	// Learn how to customize:
	// https://docs.nativescript.org/webpack
	webpack.Utils.addCopyRule('assets/**');
	webpack.Utils.addCopyRule('fonts/**');

	webpack.chainWebpack(config => {
		config.resolve.alias.set('image-source', "@nativescript/core/image-source");
		config.resolve.alias.set('tns-core-modules/ui/frame', "@nativescript/core/ui/frame");
		config.resolve.alias.set('ui/frame', "@nativescript/core/ui/frame");
		config.resolve.alias.set('application', "@nativescript/core/application");
	});
	
	webpack.chainWebpack(config => {
		config.plugin('DefinePlugin').tap(args => {
			Object.assign(args[0], {
				'global.TNS_WEBPACK': 'true',
				'global.isAndroid': env.android,
				'global.isIOS': env.ios,
				process: 'global.process'
			})

			return args;
		})
	});

	return webpack.resolveConfig();
};
```

**Comment by edusperoni** [comment] 2021-06-16 15:56
@Bidou44 you seem to be using some outdated imports, which might be the reason things are breaking down.
Have you removed `tns-core-modules` from your package.json?

Ideally those aliases shouldn't be there.

I'm saying this because the error is coming from:
```
./node_modules/@nativescript/core/ui/styling/style-scope.js 2:0-46 201:32-40
```
Which points to line 2 and line 201:
```typescript
// line 2
import { parse as parseCss } from '../../css';
// line 201
this._ast = parseCss(this._source, { source: this._file });
```

It seems your project is getting confused and resolving `../../css` to `node_modules/css` instead of `node_modules/@nativescript/core/css`.

We recommend always importing from `@nativescript/core` when possible and ditching deep imports.

**Comment by Bidou44** [comment] 2021-06-17 06:11
@edusperoni I don't have any direct references to tns-core-modules, but I'm using some plugins like nativescript-contacts that are still using it (this is why I have those alias in my webpack.config.js.

Everything was working fine with nativescript 8 and angular 11. This problem came after migrating to angular 12. In my opinion, it has something to do with the way that polyfill is loaded by angular 12.
Maybe some configurations that must be done in webpack.config.js? https://stackoverflow.com/questions/64557638/how-to-polyfill-node-core-modules-in-webpack-5

**Comment by edusperoni** [comment] 2021-06-17 09:58
@Bidou44 other than polyfills being loaded in a separate file (polyfills.ts) and using the new AngularWebpackPlugin nothing changed in the webpack config from 11 to 12. All projects we tested don't have this issue either.

The issue is that for some reason your project is resolving to the wrong "css" directory, no node modules need to be polyfilled as node_modules/css should never be used in the app.

**Comment by edusperoni** [comment] 2021-06-17 10:08
@Bidou44 can you try editing `node_modules/@nativescript/core/css/package.json` and changing the "name" to "ns-css"?

**Comment by Bidou44** [comment] 2021-06-17 11:15
I tried to change the name from "css" to "ns-css" as you suggested but it didn't help, I still have the same issue.
What I noticed is that even if the build fails with the error mentionned above, the app tries to start in the emulator and I then see the following (not sure that it helps):

System.err: An uncaught Exception occurred on "main" thread.
System.err: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Error calling module function 
System.err: TypeError: Cannot read property 'ios' of undefined
System.err: File: (file: src/webpack:/xxx/node_modules/@nativescript/core/ui/builder/index.js:10:12)
System.err: 
System.err: StackTrace: 
System.err: ./node_modules/@nativescript/core/ui/builder/index.js(file: src/webpack:/xxx/node_modules/@nativescript/core/ui/builder/index.js:10:12)
System.err: 	at __webpack_require__(file: src/webpack:/xxx/webpack/bootstrap:19:0)
System.err: 	at ./node_modules/@nativescript/core/ui/core/view/view-common.js(file:///data/data/yyy/files/app/vendor.js:92384:66)
System.err: 	at __webpack_require__(file: src/webpack:/xxx/webpack/bootstrap:19:0)
System.err: 	at ./node_modules/@nativescript/core/ui/core/view/index.android.js(file:///data/data/yyy/files/app/vendor.js:91246:70)
System.err: 	at __webpack_require__(file: src/webpack:/xxx/webpack/bootstrap:19:0)
System.err: 	at ./node_modules/@nativescript/core/ui/content-view/index.js(file:///data/data/yyy/files/app/vendor.js:88224:68)
System.err: 	at __webpack_require__(file: src/webpack:/xxx/webpack/bootstrap:19:0)
System.err: 	at ./node_modules/@nativescript/core/ui/page/page-common.js(file:///data/data/yyy/files/app/vendor.js:102990:71)
System.err: 	at __webpack_require__(file: src/webpack:/xxx/webpack/bootstrap:19:0)
System.err: 	at ./node_modules/@nativescript/core/ui/page/index.android.js(file:///data/data/yyy/files/app/vendor.js:102829:70)
System.err: 	at __webpack_require__(file: src/webpack:/xxx/webpack/bootstrap:19:0)
System.err: 	at ./node_modules/@nativescript/core/ui/frame/frame-common.js(file:///data/data/yyy/files/app/vendor.js:95685:63)
System.err: 	at __webpack_require__(file: src/webpack:/xxx/webpack/bootstrap:19:0)
System.err: 	at ./node_modules/@nativescript/core/ui/frame/index.android.js(file:///data/data/yyy/files/app/vendor.js:96455:71)
System.err: 	at __webpack_require__(file: src/webpack:/xxx/webpack/bootstrap:19:0)
System.err: 	at ./node_modules/@nativescript/core/ui/dialogs/dialogs-common.js(file:///data/data/yyy/files/app/vendor.js:93862:64)
System.err: 	at __webpack_require__(file: src/webpack:/xxx/webpack/bootstrap:19:0)
System.err: 	at ./node_modules/@nativescript/core/ui/dialogs/index.android.js(file:///data/data/yyy/files/app/vendor.js:94050:73)
System.err: 	at __webpack_require__(file: src/webpack:/xxx/webpack/bootstrap:19:0)
System.err: 	at (file: src/webpack:/xxx/node_modules/@nativescript/core/globals/index.js:259:50)
System.err: 	at loadModule(file: src/webpack:/xxx/node_modules/@nativescript/core/globals/index.js:202:0)
System.err: 	at get(file: src/webpack:/xxx/node_modules/@nativescript/core/globals/index.js:8:0)
System.err: 	at patchMethod(file: src/webpack:/xxx/node_modules/zone.js/fesm2015/zone.js:968:0)
System.err: 	at (file: src/webpack:/xxx/node_modules/zone.js/fesm2015/zone.js:2741:0)
System.err: 	at __load_patch(file: src/webpack:/xxx/node_modules/zone.js/fesm2015/zone.js:91:0)
System.err: 	at ./node_modules/zone.js/fesm2015/zone.js(file: src/webpack:/xxx/node_modules/zone.js/fesm2015/zone.js:2737:0)
System.err: 	at __webpack_require__(file: src/webpack:/xxx/webpack/bootstrap:19:0)
System.err: 	at ./src/polyfills.ts(file:///data/data/yyy/files/app/bundle.js:12112:65)
System.err: 	at __webpack_require__(file: src/webpack:/xxx/webpack/bootstrap:19:0)
System.err: 	at __webpack_exec__(file:///data/data/yyy/files/app/bundle.js:12447:39)
System.err: 	at (file:///data/data/yyy/files/app/bundle.js:12448:71)
System.err: 	at __webpack_require__.X(file: src/webpack:/xxx/webpack/runtime/startup entrypoint:6:0)
System.err: 	at (file:///data/data/yyy/files/app/bundle.js:12448:47)
System.err: 	at (file:///data/data/yyy/files/app/bundle.js:12453:3)
System.err: 	at require(:1:266)
System.err: 
System.err: 
System.err: TypeError: Cannot read property 'ios' of undefined
System.err: 
System.err: StackTrace:
System.err: java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Error calling module function 
System.err: TypeError: Cannot read property 'ios' of undefined
System.err: File: (file: src/webpack:/xxx/node_modules/@nativescript/core/ui/builder/index.js:10:12)
System.err: 
System.err: StackTrace: 
System.err: ./node_modules/@nativescript/core/ui/builder/index.js(file: src/webpack:/xxx/node_modules/@nativescript/core/ui/builder/index.js:10:12)
System.err: 	at __webpack_require__(file: src/webpack:/xxx/webpack/bootstrap:19:0)
System.err: 	at ./node_modules/@nativescript/core/ui/core/view/view-common.js(file:///data/data/yyy/files/app/vendor.js:92384:66)
System.err: 	at __webpack_require__(file: src/webpack:/xxx/webpack/bootstrap:19:0)
System.err: 	at ./node_modules/@nativescript/core/ui/core/view/index.android.js(file:///data/data/yyy/files/app/vendor.js:91246:70)
System.err: 	at __webpack_require__(file: src/webpack:/xxx/webpack/bootstrap:19:0)
System.err: 	at ./node_modules/@nativescript/core/ui/content-view/index.js(file:///data/data/yyy/files/app/vendor.js:88224:68)
System.err: 	at __webpack_require__(file: src/webpack:/xxx/webpack/bootstrap:19:0)
System.err: 	at ./node_modules/@nativescript/core/ui/page/page-common.js(file:///data/data/yyy/files/app/vendor.js:102990:71)
System.err: 	at __webpack_require__(file: src/webpack:/xxx/webpack/bootstrap:19:0)
System.err: 	at ./node_modules/@nativescript/core/ui/page/index.android.js(file:///data/data/yyy/files/app/vendor.js:102829:70)
System.err: 	at __webpack_require__(file: src/webpack:/xxx/webpack/bootstrap:19:0)
System.err: 	at ./node_modules/@nativescript/core/ui/frame/frame-common.js(file:///data/data/yyy/files/app/vendor.js:95685:63)
System.err: 	at __webpack_require__(file: src/webpack:/xxx/webpack/bootstrap:19:0)
System.err: 	at ./node_modules/@nativescript/core/ui/frame/index.android.js(file:///data/data/yyy/files/app/vendor.js:96455:71)
System.err: 	at __webpack_require__(file: src/webpack:/xxx/webpack/bootstrap:19:0)
System.err: 	at ./node_modules/@nativescript/core/ui/dialogs/dialogs-common.js(file:///data/data/yyy/files/app/vendor.js:93862:64)
System.err: 	at __webpack_require__(file: src/webpack:/xxx/webpack/bootstrap:19:0)
System.err: 	at ./node_modules/@nativescript/core/ui/dialogs/index.android.js(file:///data/data/yyy/files/app/vendor.js:94050:73)
System.err: 	at __webpack_require__(file: src/webpack:/xxx/webpack/bootstrap:19:0)
System.err: 	at (file: src/webpack:/xxx/node_modules/@nativescript/core/globals/index.js:259:50)
System.err: 	at loadModule(file: src/webpack:/xxx/node_modules/@nativescript/core/globals/index.js:202:0)
System.err: 	at get(file: src/webpack:/xxx/node_modules/@nativescript/core/globals/index.js:8:0)
System.err: 	at patchMethod(file: src/webpack:/xxx/node_modules/zone.js/fesm2015/zone.js:968:0)
System.err: 	at (file: src/webpack:/xxx/node_modules/zone.js/fesm2015/zone.js:2741:0)
System.err: 	at __load_patch(file: src/webpack:/xxx/node_modules/zone.js/fesm2015/zone.js:91:0)
System.err: 	at ./node_modules/zone.js/fesm2015/zone.js(file: src/webpack:/xxx/node_modules/zone.js/fesm2015/zone.js:2737:0)
System.err: 	at __webpack_require__(file: src/webpack:/xxx/webpack/bootstrap:19:0)
System.err: 	at ./src/polyfills.ts(file:///data/data/yyy/files/app/bundle.js:12112:65)
System.err: 	at __webpack_require__(file: src/webpack:/xxx/webpack/bootstrap:19:0)
System.err: 	at __webpack_exec__(file:///data/data/yyy/files/app/bundle.js:12447:39)
System.err: 	at (file:///data/data/yyy/files/app/bundle.js:12448:71)
System.err: 	at __webpack_require__.X(file: src/webpack:/xxx/webpack/runtime/startup entrypoint:6:0)
System.err: 	at (file:///data/data/yyy/files/app/bundle.js:12448:47)
System.err: 	at (file:///data/data/yyy/files/app/bundle.js:12453:3)
System.err: 	at require(:1:266)
System.err: 
System.err: 
System.err: TypeError: Cannot read property 'ios' of undefined
System.err: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6465)
System.err: 	at android.app.ActivityThread.access$1300(ActivityThread.java:219)
System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
System.err: 	at android.os.Handler.dispatchMessage(Handler.java:107)
System.err: 	at android.os.Looper.loop(Looper.java:214)
System.err: 	at android.app.ActivityThread.main(ActivityThread.java:7356)
System.err: 	at java.lang.reflect.Method.invoke(Native Method)
System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
System.err: Caused by: com.tns.NativeScriptException: Error calling module function 
System.err: TypeError: Cannot read property 'ios' of undefined
System.err: File: (file: src/webpack:/xxx/node_modules/@nativescript/core/ui/builder/index.js:10:12)
System.err: 
System.err: StackTrace: 
System.err: ./node_modules/@nativescript/core/ui/builder/index.js(file: src/webpack:/xxx/node_modules/@nativescript/core/ui/builder/index.js:10:12)
System.err: 	at __webpack_require__(file: src/webpack:/xxx/webpack/bootstrap:19:0)
System.err: 	at ./node_modules/@nativescript/core/ui/core/view/view-common.js(file:///data/data/yyy/files/app/vendor.js:92384:66)
System.err: 	at __webpack_require__(file: src/webpack:/xxx/webpack/bootstrap:19:0)
System.err: 	at ./node_modules/@nativescript/core/ui/core/view/index.android.js(file:///data/data/yyy/files/app/vendor.js:91246:70)
System.err: 	at __webpack_require__(file: src/webpack:/xxx/webpack/bootstrap:19:0)
System.err: 	at ./node_modules/@nativescript/core/ui/content-view/index.js(file:///data/data/yyy/files/app/vendor.js:88224:68)
System.err: 	at __webpack_require__(file: src/webpack:/xxx/webpack/bootstrap:19:0)
System.err: 	at ./node_modules/@nativescript/core/ui/page/page-common.js(file:///data/data/yyy/files/app/vendor.js:102990:71)
System.err: 	at __webpack_require__(file: src/webpack:/xxx/webpack/bootstrap:19:0)
System.err: 	at ./node_modules/@nativescript/core/ui/page/index.android.js(file:///data/data/yyy/files/app/vendor.js:102829:70)
System.err: 	at __webpack_require__(file: src/webpack:/xxx/webpack/bootstrap:19:0)
System.err: 	at ./node_modules/@nativescript/core/ui/frame/frame-common.js(file:///data/data/yyy/files/app/vendor.js:95685:63)
System.err: 	at __webpack_require__(file: src/webpack:/xxx/webpack/bootstrap:19:0)
System.err: 	at ./node_modules/@nativescript/core/ui/frame/index.android.js(file:///data/data/yyy/files/app/vendor.js:96455:71)
System.err: 	at __webpack_require__(file: src/webpack:/xxx/webpack/bootstrap:19:0)
System.err: 	at ./node_modules/@nativescript/core/ui/dialogs/dialogs-common.js(file:///data/data/yyy/files/app/vendor.js:93862:64)
System.err: 	at __webpack_require__(file: src/webpack:/xxx/webpack/bootstrap:19:0)
System.err: 	at ./node_modules/@nativescript/core/ui/dialogs/index.android.js(file:///data/data/yyy/files/app/vendor.js:94050:73)
System.err: 	at __webpack_require__(file: src/webpack:/xxx/webpack/bootstrap:19:0)
System.err: 	at (file: src/webpack:/xxx/node_modules/@nativescript/core/globals/index.js:259:50)
System.err: 	at loadModule(file: src/webpack:/xxx/node_modules/@nativescript/core/globals/index.js:202:0)
System.err: 	at get(file: src/webpack:/xxx/node_modules/@nativescript/core/globals/index.js:8:0)
System.err: 	at patchMethod(file: src/webpack:/xxx/node_modules/zone.js/fesm2015/zone.js:968:0)
System.err: 	at (file: src/webpack:/xxx/node_modules/zone.js/fesm2015/zone.js:2741:0)
System.err: 	at __load_patch(file: src/webpack:/xxx/node_modules/zone.js/fesm2015/zone.js:91:0)
System.err: 	at ./node_modules/zone.js/fesm2015/zone.js(file: src/webpack:/xxx/node_modules/zone.js/fesm2015/zone.js:2737:0)
System.err: 	at __webpack_require__(file: src/webpack:/xxx/webpack/bootstrap:19:0)
System.err: 	at ./src/polyfills.ts(file:///data/data/yyy/files/app/bundle.js:12112:65)
System.err: 	at __webpack_require__(file: src/webpack:/xxx/webpack/bootstrap:19:0)
System.err: 	at __webpack_exec__(file:///data/data/yyy/files/app/bundle.js:12447:39)
System.err: 	at (file:///data/data/yyy/files/app/bundle.js:12448:71)
System.err: 	at __webpack_require__.X(file: src/webpack:/xxx/webpack/runtime/startup entrypoint:6:0)
System.err: 	at (file:///data/data/yyy/files/app/bundle.js:12448:47)
System.err: 	at (file:///data/data/yyy/files/app/bundle.js:12453:3)
System.err: 	at require(:1:266)
System.err: 
System.err: 
System.err: TypeError: Cannot read property 'ios' of undefined
System.err: 	at com.tns.Runtime.runModule(Native Method)
System.err: 	at com.tns.Runtime.runModule(Runtime.java:689)
System.err: 	at com.tns.Runtime.run(Runtime.java:681)
System.err: 	at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:21)
System.err: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1182)
System.err: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6460)
System.err: 	... 8 more

**Comment by Bidou44** [comment] 2021-06-25 08:12
@edusperoni Small update on this problem: 
Removing the following packages from my package.json made the application work:

    "util": "^0.12.4",
    "platform": "~1.3.6"
    
  I'm not closing this issue as I'm still seeing the errors mentionned above... but at least the application is starting...

**Comment by lambourn** [comment] 2021-07-02 07:30
we're experiencing the same issue...

**Comment by Bidou44** [comment] 2021-07-02 07:59
I finally managed to made it work.... I had to replace the `path` property of the tsconfig.json

**OLD:**
```
        "paths": {
            "~/*": [
                "./src/*",
            ],
            "*": [
                "./node_modules/tns-core-modules/*",
                "./node_modules/*"
            ]
        }
```

**NEW**
```
        "paths": {
            "~/*": ["src/*"],
            "@/*": ["src/*"]
          }
```

Hope it helps

**Comment by lambourn** [comment] 2021-07-02 08:00
@Bidou44 nice - I will try that and get back here

**Closed** 2021-07-05 05:18 UTC
