### ISSUE TITLE
HMR does not work (Angular)

### ISSUE THREAD

**Issue by Bezlepkin** [NativeScript/angular#50] opened 2022-01-15 19:41 UTC
**Environment**
 - CLI: 8.0.2
 - Android Runtime: 8.1.1
 - iOS Runtime:8.1.0
 - NativeScript-Angular: 13.0.0
 - Angular: 13.1.1

HMR does not work as it should. Only with the --no-hmr flag the application is restarted.

**Comment by edusperoni** [comment] 2022-01-15 19:43
Hello!

HMR is working for me, so please provide more information and reproduction steps.

**Comment by Bezlepkin** [comment] 2022-01-15 19:57
> Hello!
> 
> HMR is working for me, so please provide more information and reproduction steps.

That is, you can insert a button, save and the UI will update without restarting the application?

**Comment by edusperoni** [comment] 2022-01-16 06:03
Yes!

Unfortunately it seems to be a bit inconsistent due to the `.mjs` migration of 13 and some webpack update (*sometimes* the application actually restarted instead of hot applying), but I'll deploy a fix shortly to cover that edge case. That said, the worst case scenario was the application restarting instead of hot reloading, which is not what you said your problem was (needing to use --no-hmr for a restart).

It is common practice to provide the actual steps to reproduce the error, the exact behavior that is happening and the behavior you're expecting.

**Comment by NathanWalker** [comment] 2022-01-17 00:40
closed via https://github.com/NativeScript/angular/pull/51

**Closed by NathanWalker** 2022-01-17 00:40 UTC

**Comment by Bezlepkin** [comment] 2022-01-17 06:09
Everything worked! Thanks!
